[package]
name = "rustyBackend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
<<<<<<< HEAD
futures = "0.3.30"
lazy_static = "1.5.0"
rocket = "0.5.0"
tokio = { version = "1.39.1", features = ["full"] }
=======
rocket = "0.5.0"
>>>>>>> parent of bf02cb4 (Fixes)
